### ISSUE TITLE
First Mission won't work

### ISSUE THREAD

**Issue by YoruToboe** [sayterdarkwynd/FrackinUniverse_RC#116]
When i try to launch the Mission "Visit Science Outpost" i teleport, runs the teleportation loading thing then i appear at my ship again. I am running the FrackinUniverse_v1399b on Spirited Giraffe on the update that happened April 21

**Comment by sayterdarkwynd** [comment]
yea, im on that, dont worry. Fix just got pushed :)

On Wed, Apr 22, 2015 at 4:58 AM, YoruToboe <notifications@github.com> wrote:

> When i try to launch the Mission "Visit Science Outpost" i teleport, runs
> the teleportation loading thing then i appear at my ship again. I am
> running the FrackinUniverse_v1399b on Spirited Giraffe on the update that
> happened yesterday
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sayterdarkwynd/FrackinUniverse_RC/issues/116>.
>



-- 
Chris DeChamplain
Graphic/Web Designer
