### ISSUE TITLE
Error: Fatal Exception caught: (MapException) Key 'bioooze' not found in Map::get()

### ISSUE THREAD

**Issue by AllSystemsGo** [sayterdarkwynd/FrackinUniverse_RC#139]
Pulled tonight. I know it's not a release but I at least did want to advise of the following.

[starbound.log.txt](https://github.com/sayterdarkwynd/FrackinUniverse_RC/files/60343/starbound.log.txt)

edit: I've isolated the steps to reproduce.
1. Make a new character and enter a universe on a randomized planet.
2. Watch the logs for errors related to map key exceptions and bioooze. If none appear, repeat step 1.
3. Quit the game. On restart, it will crash with the error Error: Fatal Exception caught: (MapException) Key 'bioooze' not found in Map::get()

**Comment by sayterdarkwynd** [comment]
should be fixed already. only just noticd this now lol
