### ISSUE TITLE
fuaviansentry: Error: Exception while invoking lua function 'damage'. (LuaException) Error code 2, [string "/monsters/fuaviansentry/behavior.lua"]

### ISSUE THREAD

**Issue by AllSystemsGo** [sayterdarkwynd/FrackinUniverse_RC#141]
Appeared on current version up to/including commits on 12/18/15.

[22:06:38.411] Error: Exception while invoking lua function 'damage'. (LuaException) Error code 2, [string "/monsters/fuaviansentry/behavior.lua"]:131: (LuaConversionException) Error converting LuaValue to type 'N4Star6StringE'
./starbound_server(_ZN4Star13StarExceptionC1EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x6e) [0x1188e2e]
./starbound_server(_ZN4Star22LuaConversionException6formatIIPKcEEES0_S3_DpRKT_+0x9d) [0x9a28ad]
./starbound_server(_ZN4Star5luaToINS_6StringEEET_NS_3AnyIIbxdS1_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEE+0xf4) [0x9a4294]
./starbound_server(_ZN4Star9LuaDetail6ArgGetINS_6StringEE3getEmPNS_3AnyIJbxdS2_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEm+0x6c) [0xa86dcc]
./starbound_server(_ZNSt17_Function_handlerIFN4Star3AnyIINS1_IIbxdNS0_6StringENS0_8LuaTableENS0_11LuaFunctionENS0_9LuaThreadENS0_11LuaUserDataEEEENS0_11LuaVariadicIS7_EEEEERNS0_9LuaEngineEmPS7_EZNS0_9LuaDetail15FunctionWrapperIbIS2_S2_bEE11wrapIndexesISt5_BindIFSt7_Mem_fnIMNS0_17NetworkedAnimatorEFbRKS2_SN_bEEPSL_St12_PlaceholderILi1EESS_ILi2EESS_ILi3EEEEILm0ELm1ELm2EEEESt8functionISE_ET_RKNS0_13IndexSequenceIIXspT0_EEEEEUlSC_mSD_E_E9_M_invokeERKSt9_Any_dataSC_OmOSD_+0x74) [0xfcdeb4]
./starbound_server() [0x112f3dd]
./starbound_server() [0x119cdcd]
./starbound_server() [0x11b61d5]
./starbound_server() [0x119d7e3]
./starbound_server() [0x119c292]
./starbound_server() [0x119dbf3]
./starbound_server(lua_pcallk+0x62) [0x1195e42]
./starbound_server(_ZN4Star9LuaEngine12callFunctionIINS_3MapINS_6StringENS_4JsonESt13unordered_mapIS3_S4_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_S4_EEEEEEEENS_3AnyIINSG_IIbxdS3_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEENS_11LuaVariadicISL_EEEEEiDpRKT_+0x89) [0xc33e39]
./starbound_server(_ZN4Star16LuaBaseComponent6invokeINS_3AnyIJbxdNS_6StringENS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEJNS_3MapIS3_NS_4JsonESt13unordered_mapIS3_SA_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_SA_EEEEEEEENS_5MaybeIT_EERSH_DpOT0_+0x110) [0xc34370]
./starbound_server(_ZN4Star7Monster11applyDamageERKNS_13DamageRequestE+0x1b5) [0xc1a855]
./starbound_server(_ZN4Star13DamageManager23pushRemoteDamageRequestERKNS_19RemoteDamageRequestE+0x64) [0xb46464]
./starbound_server(_ZN4Star13DamageManager16addDamageRequestENS_19RemoteDamageRequestE+0x1e3) [0xb46913]
./starbound_server() [0xb47355]
./starbound_server(_ZNK4Star11WorldServer14forAllEntitiesESt8functionIFvRKSt10shared_ptrINS_6EntityEEEE+0x34) [0x9c1054]
./starbound_server(_ZN4Star13DamageManager6updateEv+0x140) [0xb45610]
./starbound_server(_ZN4Star11WorldServer12updateDamageEv+0x2a) [0x9d456a]
./starbound_server(_ZN4Star11WorldServer6updateEv+0x472) [0x9d7d32]
./starbound_server(_ZN4Star17WorldServerThread6updateEv+0x262) [0xa093d2]
./starbound_server(_ZN4Star17WorldServerThread3runEv+0x348) [0xa09d98]
./starbound_server(_ZN4Star10ThreadImpl9runThreadEPv+0x1a) [0x119201a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4) [0x7f44c230f0a4]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f44c1b3f04d]
./starbound_server(_ZN4Star13StarExceptionC1EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x6e) [0x1188e2e]
./starbound_server(_ZN4Star12LuaExceptionC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x58) [0xa8f2c8]
./starbound_server(_ZN4Star9LuaEngine11handleErrorEP9lua_Statei+0x412) [0x11282e2]
./starbound_server(_ZN4Star9LuaEngine12callFunctionIINS_3MapINS_6StringENS_4JsonESt13unordered_mapIS3_S4_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_S4_EEEEEEEENS_3AnyIINSG_IIbxdS3_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEENS_11LuaVariadicISL_EEEEEiDpRKT_+0xa1) [0xc33e51]
./starbound_server(_ZN4Star16LuaBaseComponent6invokeINS_3AnyIJbxdNS_6StringENS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEJNS_3MapIS3_NS_4JsonESt13unordered_mapIS3_SA_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_SA_EEEEEEEENS_5MaybeIT_EERSH_DpOT0_+0x110) [0xc34370]
./starbound_server(_ZN4Star7Monster11applyDamageERKNS_13DamageRequestE+0x1b5) [0xc1a855]
./starbound_server(_ZN4Star13DamageManager23pushRemoteDamageRequestERKNS_19RemoteDamageRequestE+0x64) [0xb46464]
./starbound_server(_ZN4Star13DamageManager16addDamageRequestENS_19RemoteDamageRequestE+0x1e3) [0xb46913]
./starbound_server() [0xb47355]
./starbound_server(_ZNK4Star11WorldServer14forAllEntitiesESt8functionIFvRKSt10shared_ptrINS_6EntityEEEE+0x34) [0x9c1054]
./starbound_server(_ZN4Star13DamageManager6updateEv+0x140) [0xb45610]
./starbound_server(_ZN4Star11WorldServer12updateDamageEv+0x2a) [0x9d456a]
./starbound_server(_ZN4Star11WorldServer6updateEv+0x472) [0x9d7d32]
./starbound_server(_ZN4Star17WorldServerThread6updateEv+0x262) [0xa093d2]
./starbound_server(_ZN4Star17WorldServerThread3runEv+0x348) [0xa09d98]
./starbound_server(_ZN4Star10ThreadImpl9runThreadEPv+0x1a) [0x119201a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4) [0x7f44c230f0a4]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f44c1b3f04d]
[22:06:38.416] Error: Exception while invoking lua function 'damage'. (LuaException) Error code 2, [string "/monsters/fuaviansentry/behavior.lua"]:131: (LuaConversionException) Error converting LuaValue to type 'N4Star6StringE'
./starbound_server(_ZN4Star13StarExceptionC1EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x6e) [0x1188e2e]
./starbound_server(_ZN4Star22LuaConversionException6formatIIPKcEEES0_S3_DpRKT_+0x9d) [0x9a28ad]
./starbound_server(_ZN4Star5luaToINS_6StringEEET_NS_3AnyIIbxdS1_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEE+0xf4) [0x9a4294]
./starbound_server(_ZN4Star9LuaDetail6ArgGetINS_6StringEE3getEmPNS_3AnyIJbxdS2_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEm+0x6c) [0xa86dcc]
./starbound_server(_ZNSt17_Function_handlerIFN4Star3AnyIINS1_IIbxdNS0_6StringENS0_8LuaTableENS0_11LuaFunctionENS0_9LuaThreadENS0_11LuaUserDataEEEENS0_11LuaVariadicIS7_EEEEERNS0_9LuaEngineEmPS7_EZNS0_9LuaDetail15FunctionWrapperIbIS2_S2_bEE11wrapIndexesISt5_BindIFSt7_Mem_fnIMNS0_17NetworkedAnimatorEFbRKS2_SN_bEEPSL_St12_PlaceholderILi1EESS_ILi2EESS_ILi3EEEEILm0ELm1ELm2EEEESt8functionISE_ET_RKNS0_13IndexSequenceIIXspT0_EEEEEUlSC_mSD_E_E9_M_invokeERKSt9_Any_dataSC_OmOSD_+0x74) [0xfcdeb4]
./starbound_server() [0x112f3dd]
./starbound_server() [0x119cdcd]
./starbound_server() [0x11b61d5]
./starbound_server() [0x119d7e3]
./starbound_server() [0x119c292]
./starbound_server() [0x119dbf3]
./starbound_server(lua_pcallk+0x62) [0x1195e42]
./starbound_server(_ZN4Star9LuaEngine12callFunctionIINS_3MapINS_6StringENS_4JsonESt13unordered_mapIS3_S4_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_S4_EEEEEEEENS_3AnyIINSG_IIbxdS3_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEENS_11LuaVariadicISL_EEEEEiDpRKT_+0x89) [0xc33e39]
./starbound_server(_ZN4Star16LuaBaseComponent6invokeINS_3AnyIJbxdNS_6StringENS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEJNS_3MapIS3_NS_4JsonESt13unordered_mapIS3_SA_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_SA_EEEEEEEENS_5MaybeIT_EERSH_DpOT0_+0x110) [0xc34370]
./starbound_server(_ZN4Star7Monster11applyDamageERKNS_13DamageRequestE+0x1b5) [0xc1a855]
./starbound_server(_ZN4Star13DamageManager23pushRemoteDamageRequestERKNS_19RemoteDamageRequestE+0x64) [0xb46464]
./starbound_server(_ZN4Star13DamageManager16addDamageRequestENS_19RemoteDamageRequestE+0x1e3) [0xb46913]
./starbound_server() [0xb47355]
./starbound_server(_ZNK4Star11WorldServer14forAllEntitiesESt8functionIFvRKSt10shared_ptrINS_6EntityEEEE+0x34) [0x9c1054]
./starbound_server(_ZN4Star13DamageManager6updateEv+0x140) [0xb45610]
./starbound_server(_ZN4Star11WorldServer12updateDamageEv+0x2a) [0x9d456a]
./starbound_server(_ZN4Star11WorldServer6updateEv+0x472) [0x9d7d32]
./starbound_server(_ZN4Star17WorldServerThread6updateEv+0x262) [0xa093d2]
./starbound_server(_ZN4Star17WorldServerThread3runEv+0x348) [0xa09d98]
./starbound_server(_ZN4Star10ThreadImpl9runThreadEPv+0x1a) [0x119201a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4) [0x7f44c230f0a4]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f44c1b3f04d]
./starbound_server(_ZN4Star13StarExceptionC1EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x6e) [0x1188e2e]
./starbound_server(_ZN4Star12LuaExceptionC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x58) [0xa8f2c8]
./starbound_server(_ZN4Star9LuaEngine11handleErrorEP9lua_Statei+0x412) [0x11282e2]
./starbound_server(_ZN4Star9LuaEngine12callFunctionIINS_3MapINS_6StringENS_4JsonESt13unordered_mapIS3_S4_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_S4_EEEEEEEENS_3AnyIINSG_IIbxdS3_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEENS_11LuaVariadicISL_EEEEEiDpRKT_+0xa1) [0xc33e51]
./starbound_server(_ZN4Star16LuaBaseComponent6invokeINS_3AnyIJbxdNS_6StringENS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEJNS_3MapIS3_NS_4JsonESt13unordered_mapIS3_SA_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_SA_EEEEEEEENS_5MaybeIT_EERSH_DpOT0_+0x110) [0xc34370]
./starbound_server(_ZN4Star7Monster11applyDamageERKNS_13DamageRequestE+0x1b5) [0xc1a855]
./starbound_server(_ZN4Star13DamageManager23pushRemoteDamageRequestERKNS_19RemoteDamageRequestE+0x64) [0xb46464]
./starbound_server(_ZN4Star13DamageManager16addDamageRequestENS_19RemoteDamageRequestE+0x1e3) [0xb46913]
./starbound_server() [0xb47355]
./starbound_server(_ZNK4Star11WorldServer14forAllEntitiesESt8functionIFvRKSt10shared_ptrINS_6EntityEEEE+0x34) [0x9c1054]
./starbound_server(_ZN4Star13DamageManager6updateEv+0x140) [0xb45610]
./starbound_server(_ZN4Star11WorldServer12updateDamageEv+0x2a) [0x9d456a]
./starbound_server(_ZN4Star11WorldServer6updateEv+0x472) [0x9d7d32]
./starbound_server(_ZN4Star17WorldServerThread6updateEv+0x262) [0xa093d2]
./starbound_server(_ZN4Star17WorldServerThread3runEv+0x348) [0xa09d98]
./starbound_server(_ZN4Star10ThreadImpl9runThreadEPv+0x1a) [0x119201a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4) [0x7f44c230f0a4]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f44c1b3f04d]
[22:06:40.850] Error: Exception while invoking lua function 'damage'. (LuaException) Error code 2, [string "/monsters/fuaviansentry/behavior.lua"]:131: (LuaConversionException) Error converting LuaValue to type 'N4Star6StringE'
./starbound_server(_ZN4Star13StarExceptionC1EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x6e) [0x1188e2e]
./starbound_server(_ZN4Star22LuaConversionException6formatIIPKcEEES0_S3_DpRKT_+0x9d) [0x9a28ad]
./starbound_server(_ZN4Star5luaToINS_6StringEEET_NS_3AnyIIbxdS1_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEE+0xf4) [0x9a4294]
./starbound_server(_ZN4Star9LuaDetail6ArgGetINS_6StringEE3getEmPNS_3AnyIJbxdS2_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEm+0x6c) [0xa86dcc]
./starbound_server(_ZNSt17_Function_handlerIFN4Star3AnyIINS1_IIbxdNS0_6StringENS0_8LuaTableENS0_11LuaFunctionENS0_9LuaThreadENS0_11LuaUserDataEEEENS0_11LuaVariadicIS7_EEEEERNS0_9LuaEngineEmPS7_EZNS0_9LuaDetail15FunctionWrapperIbIS2_S2_bEE11wrapIndexesISt5_BindIFSt7_Mem_fnIMNS0_17NetworkedAnimatorEFbRKS2_SN_bEEPSL_St12_PlaceholderILi1EESS_ILi2EESS_ILi3EEEEILm0ELm1ELm2EEEESt8functionISE_ET_RKNS0_13IndexSequenceIIXspT0_EEEEEUlSC_mSD_E_E9_M_invokeERKSt9_Any_dataSC_OmOSD_+0x74) [0xfcdeb4]
./starbound_server() [0x112f3dd]
./starbound_server() [0x119cdcd]
./starbound_server() [0x11b61d5]
./starbound_server() [0x119d7e3]
./starbound_server() [0x119c292]
./starbound_server() [0x119dbf3]
./starbound_server(lua_pcallk+0x62) [0x1195e42]
./starbound_server(_ZN4Star9LuaEngine12callFunctionIINS_3MapINS_6StringENS_4JsonESt13unordered_mapIS3_S4_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_S4_EEEEEEEENS_3AnyIINSG_IIbxdS3_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEENS_11LuaVariadicISL_EEEEEiDpRKT_+0x89) [0xc33e39]
./starbound_server(_ZN4Star16LuaBaseComponent6invokeINS_3AnyIJbxdNS_6StringENS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEJNS_3MapIS3_NS_4JsonESt13unordered_mapIS3_SA_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_SA_EEEEEEEENS_5MaybeIT_EERSH_DpOT0_+0x110) [0xc34370]
./starbound_server(_ZN4Star7Monster11applyDamageERKNS_13DamageRequestE+0x1b5) [0xc1a855]
./starbound_server(_ZN4Star13DamageManager23pushRemoteDamageRequestERKNS_19RemoteDamageRequestE+0x64) [0xb46464]
./starbound_server(_ZN4Star13DamageManager16addDamageRequestENS_19RemoteDamageRequestE+0x1e3) [0xb46913]
./starbound_server() [0xb47355]
./starbound_server(_ZNK4Star11WorldServer14forAllEntitiesESt8functionIFvRKSt10shared_ptrINS_6EntityEEEE+0x34) [0x9c1054]
./starbound_server(_ZN4Star13DamageManager6updateEv+0x140) [0xb45610]
./starbound_server(_ZN4Star11WorldServer12updateDamageEv+0x2a) [0x9d456a]
./starbound_server(_ZN4Star11WorldServer6updateEv+0x472) [0x9d7d32]
./starbound_server(_ZN4Star17WorldServerThread6updateEv+0x262) [0xa093d2]
./starbound_server(_ZN4Star17WorldServerThread3runEv+0x348) [0xa09d98]
./starbound_server(_ZN4Star10ThreadImpl9runThreadEPv+0x1a) [0x119201a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4) [0x7f44c230f0a4]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f44c1b3f04d]
./starbound_server(_ZN4Star13StarExceptionC1EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x6e) [0x1188e2e]
./starbound_server(_ZN4Star12LuaExceptionC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x58) [0xa8f2c8]
./starbound_server(_ZN4Star9LuaEngine11handleErrorEP9lua_Statei+0x412) [0x11282e2]
./starbound_server(_ZN4Star9LuaEngine12callFunctionIINS_3MapINS_6StringENS_4JsonESt13unordered_mapIS3_S4_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_S4_EEEEEEEENS_3AnyIINSG_IIbxdS3_NS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEENS_11LuaVariadicISL_EEEEEiDpRKT_+0xa1) [0xc33e51]
./starbound_server(_ZN4Star16LuaBaseComponent6invokeINS_3AnyIJbxdNS_6StringENS_8LuaTableENS_11LuaFunctionENS_9LuaThreadENS_11LuaUserDataEEEEJNS_3MapIS3_NS_4JsonESt13unordered_mapIS3_SA_NS_4hashIS3_vEESt8equal_toIS3_ESaISt4pairIKS3_SA_EEEEEEEENS_5MaybeIT_EERSH_DpOT0_+0x110) [0xc34370]
./starbound_server(_ZN4Star7Monster11applyDamageERKNS_13DamageRequestE+0x1b5) [0xc1a855]
./starbound_server(_ZN4Star13DamageManager23pushRemoteDamageRequestERKNS_19RemoteDamageRequestE+0x64) [0xb46464]
./starbound_server(_ZN4Star13DamageManager16addDamageRequestENS_19RemoteDamageRequestE+0x1e3) [0xb46913]
./starbound_server() [0xb47355]
./starbound_server(_ZNK4Star11WorldServer14forAllEntitiesESt8functionIFvRKSt10shared_ptrINS_6EntityEEEE+0x34) [0x9c1054]
./starbound_server(_ZN4Star13DamageManager6updateEv+0x140) [0xb45610]
./starbound_server(_ZN4Star11WorldServer12updateDamageEv+0x2a) [0x9d456a]
./starbound_server(_ZN4Star11WorldServer6updateEv+0x472) [0x9d7d32]
./starbound_server(_ZN4Star17WorldServerThread6updateEv+0x262) [0xa093d2]
./starbound_server(_ZN4Star17WorldServerThread3runEv+0x348) [0xa09d98]
./starbound_server(_ZN4Star10ThreadImpl9runThreadEPv+0x1a) [0x119201a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4) [0x7f44c230f0a4]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f44c1b3f04d]

**Comment by sayterdarkwynd** [comment]
yea, aviansentry is borked. ima just remove it.
