### ISSUE TITLE
FrackinUniverse\projectiles\guns\toxicdart\toxicdart.projectile

### ISSUE THREAD

**Issue by AllSystemsGo** [sayterdarkwynd/FrackinUniverse_RC#142]
[19:54:08.495] Error: Exception while invoking lua function 'applyDamageRequest'. (LuaException) Error code 2,
 [string "/stats/monster_primary.lua"]:31: (StatusEffectDatabaseException) No such unique stat effect 'damagef
lash'
./starbound_server(_ZN4Star13StarExceptionC1EPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x6e) [0x
1188e2e]
./starbound_server(_ZNK4Star20StatusEffectDatabase18uniqueEffectConfigERKNS_6StringE+0x1658) [0x92ffa8]
./starbound_server(_ZNK4Star16StatusController27defaultUniqueEffectDurationERKNS_6StringE+0x39) [0xe24709]
./starbound_server(_ZN4Star16StatusController19addEphemeralEffectsERKNS_4ListINS_21EphemeralStatusEffectESaIS2
_EEENS_5MaybeIiEE+0x103) [0xe2f1f3]
./starbound_server(_ZN4Star11LuaBindings25StatusControllerCallbacks19addEphemeralEffectsEPNS_16StatusControlle
rERKNS_4ListINS_4JsonESaIS5_EEENS_5MaybeIiEE+0x122) [0xfd1a42]
./starbound_server(_ZNSt17_Function_handlerIFN4Star3AnyIJNS1_IJbxdNS0_6StringENS0_8LuaTableENS0_11LuaFunctionE
NS0_9LuaThreadENS0_11LuaUserDataEEEENS0_11LuaVariadicIS7_EEEEERNS0_9LuaEngineEmPS7_EZNS0_9LuaDetail15FunctionW
rapperIvJNS0_4ListINS0_4JsonESaISI_EEENS0_5MaybeIiEEEE11wrapIndexesISt5_BindIFPFvPNS0_16StatusControllerERKSK_
SM_ESR_St12_PlaceholderILi1EESW_ILi2EEEEJLm0ELm1EEEESt8functionISE_ET_RKNS0_13IndexSequenceIJXspT0_EEEEEUlSC_m
SD_E_E9_M_invokeERKSt9_Any_dataSC_OmOSD_+0xc4) [0xfd5304]

**Comment by sayterdarkwynd** [comment]
resolved.
