### ISSUE TITLE
Normal Quantum Extractor Requires More Energy than Roof Version

### ISSUE THREAD

**Issue by moppr** [sayterdarkwynd/FrackinUniverse_RC#165]
Both also appear to extract slower than mkII extractors despite the code apparently being correct

**Comment by renbear67** [comment]
Quantum Extractor gives bonus resources, if I understand correctly. It might not be intended to be faster than the mk2. @sayterdarkwynd , any thoughts? We can speed it up if necessary.

**Comment by moppr** [comment]
From a design perspective, I'd actually prefer them to be faster with the same output, because once you're at the point in the progression to be able to make them, you generally care more about speed than efficiency. Just a random thought though. What confuses me is that the floor version takes 5u power but the roof one only takes 3u according to the descriptions. Quick testing showed that an 8000u unit could run two roof versions at once but not two floor ones.

**Comment by renbear67** [comment]
Yeah, the 3u/5u power usage is unintentional. We'll fix that. Leaving this here, though, for the other issues.
