### ISSUE TITLE
unable to unlock fisson furnace blueprint

### ISSUE THREAD

**Issue by Crysis1007** [sayterdarkwynd/FrackinUniverse_RC#191]
i am not able to unlock the fission furnace blueprint in the matter assembler. looking at the object file:  "learnBlueprintsOnPickup" : [ "solariumstar", "solaricrystal", "magnesiumpowder", "moonstonebar", "titaniumwallblockmaterial", "speedblockmaterial", "jumpblockmaterial" ] but i have picked up all of these items and still havent learned the fission furnace blueprint. i tried a brand new toon. i tried no other mods to check conflict and still nothing. please help me fix this because i can not progress in FU without the fission furnace.

attached is my log file

[starbound log.txt](https://github.com/sayterdarkwynd/FrackinUniverse_RC/files/216256/starbound.log.txt)

**Comment by sayterdarkwynd** [comment]
no, that is what the fission furnace unlocks. Not what unlocks the fission furnace. This is not a bug or an issue. You simply didn't pick up the stations that come before it. Namely, the extractor.

**Comment by Crysis1007** [comment]
Thank you for clarifying. You are correct, no issues. :-)
